%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 848
image_height: 480
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 426.4847717285156
   fy: 426.4847717285156
   cx: 429.9100646972656
   cy: 242.24940490722656
