%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 640
image_height: 480
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 386.2503662109375
   fy: 386.2503662109375
   cx: 325.3525085449219
   cy: 242.02720642089844